### ISSUE TITLE
You have to run the 64-bit version of DPInst.exe Error

### ISSUE THREAD

**Issue by pongpaktech** [analogdevicesinc/alice#11]
I am trying to get ALICE installed for my physics lab course that starts in a couple weeks. When I try to install ALICE with the precompiled binaries the libsmu installer gives me a "You have to run the 64-bit version of DPInst.exe on this machine" error (I have linked a screenshot below) and it says to contact the vendor.

I am running Windows 10 education 2004 64 bit

![libsmu-1 0 2-setup-x86 tmp_tcxM52fIkY](https://user-images.githubusercontent.com/32118013/94635679-081f2a00-0288-11eb-9684-442986c1208c.png)

**Comment by damercer** [comment]
Did you happen to check the install Winusb drivers box when it was installing libsmu (32 bit version)? From the screen shot it looks like you did. If so, don't. Use the 64 bit libsmu installer first to install Winusb drivers on a 64 bit system.

I realize this may be confusing but that is the way things are because the ALICE executable is built using 32 bit Python / libsmu.

Doug

**Comment by pongpaktech** [comment]
> 
> 
> Did you happen to check the install Winusb drivers box when it was installing libsmu (32 bit version)? From the screen shot it looks like you did. If so, don't. Use the 64 bit libsmu installer first to install Winusb drivers on a 64 bit system.
> 
> I realize this may be confusing but that is the way things are because the ALICE executable is built using 32 bit Python / libsmu.
> 
> Doug

Thank you very much Doug! I did select to install the drivers but I also already had the 64 bit one from installing Pixel Pulse software. I'll make sure to pass this onto my class
