### ISSUE TITLE
How to use Alice on Linux?

### ISSUE THREAD

**Issue by peterbuxton** [analogdevicesinc/alice#3]
I want to use Alice with Linux to work with the ADALM1000. (My Linux is Slackware 14.2 64-bit, python 2.7.11, numpy 1.8.2). I downloaded the Alice 1.3 .pyw files and successfully built the libsmu ver 1.0.2, so I believe all the requirements are in order.

Per the ADI page _User’s Guide for the ALICE Desktop software interface_, I am understanding that Alice is simply scripts fed through the python interpreter. However, I find no instructions on how to make the Alice .pyw files run in Linux and open a GUI window. I am a newbie at using python so I am probably at fault, but I have successfully run simple .py scripts in a terminal window with the command `python name.py`. I read that a .pyw file is meant for Windows, but can be run in Linux by renaming it to .py but when I try to run one, python quits with a segmentation fault. 

I would like to understand how all of this works, to hopefully create and contribute to the project. lsusb command shows my device connected on the USB. Knowing a basic python script that would verify that my ADALM1000 is listening would be helpful. I would appreciate any help to get Alice running on Linux. Thank you.

**Comment by damercer** [comment]
From the command line navigate to the directory where you have put the alice-desktop-1.3.pyw source file.
Type: python alice-desktop-1.3.pyw

Just typing python should start 2.7 but to be sure, I think python27 is also a working command.

This should start running the source code.

I almost never use Linux so I might not have this exactly right but I think from the file manager you can open the alice-desktop-1.3.pyw file using the Python IDLE editor to view and edit the file or any python source code. You can also run the file from inside the IDLE. I think there might also be a way to open the .pyw file with Python from the file manager, i.e. set it so double click will run the program. I have not had much luck making things work in Linux as I've said. But since you have chosen to use Linux it is on you to learn how to run programs from source code.

**Comment by peterbuxton** [comment]
This is a great start for me. At this point I am not yet Python literate but I will try to learn fast. I have just learned how to use Tkinter to show windows in the GUI, so I now understand better how the Alice scripts are working. It might take me a couple days to get going on this but I'll report back with my success. Knowing now about how the smu command works will definitely help me too. Thank you.

**Comment by peterbuxton** [comment]
I acknowledge that Alice is now working on my Linux PC (Slackware 14.2 distro). I haven't yet used Alice with data from the ALM1000 device, but the oscilloscope screen is up.  A message popped up saying it required ver 2.16 of the device and asked if I wanted to upgrade the firmware. I knew that it was already ver 2.16 (from running with PixelPulse 2 on Windows) so I said No. Then the message went away and I exited the Alice program. Using libsmu with the command line tools is working too. It streamed samples (zeros) to the command screen. That was enough proof to me that things are set up right. First I want to clean up and organize some things on my Linux system before testing further with the experiments on the ADI pages. I will also perform this whole setup on another Linux PC with a different distro, just for experience, and report the results.
